version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ort-crm-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ort_crm
      POSTGRES_USER: ortcrm
      POSTGRES_PASSWORD: gulkaiyrPASSWORD2004
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ortcrm -d ort_crm"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ort-crm-back
    restart: unless-stopped
    environment:
      SERVER_PORT: 8087
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ort_crm
      SPRING_DATASOURCE_USERNAME: ortcrm
      SPRING_DATASOURCE_PASSWORD: gulkaiyrPASSWORD2004
      JWT_SECRET: Jbip4pDX1RqFa0SGfoyXqhadGuC4Cd7Yg3DvCgwKRhWKIIvcWsYqUmYUOEwufd9B6tPt6F+cZxEXI7CIhKCtgQ==
      JWT_EXPIRATION: 86400000
      APP_CORS_ALLOWED_ORIGINS: http://38.180.36.182:8086
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8087:8087"

  frontend:
    build:
      context: ../ort-crm-frontend
      dockerfile: ../ort-crm/deploy/frontend.Dockerfile
    container_name: ort-crm-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8086:80"

volumes:
  postgres-data:
